# FROM golang:alpine

# RUN apk add --no-cache bash curl git

# WORKDIR /app

# COPY go.mod go.sum ./
# RUN go mod download

# COPY . .

# CMD ["go", "run", "cmd/worker/main.go"]


FROM golang:alpine

RUN apk add --no-cache \
    bash \
    curl \
    git \
    python3 \
    py3-pip

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["go", "run", "cmd/worker/main.go"]